### ISSUE TITLE
My slider on my website is not working. I can not load new slides. Can  you help me? 

### ISSUE THREAD

**Issue by ACA202** [zionbuilder/zionbuilder#104]
**Describe the bug**
*Write a explanatory description of the bug.*

**Have you tried all the steps at https://zionbuilder.io/documentation/having-problems-using-zion-builder/?**
*Yes/No*

**Steps to reproduce**

**Expected behavior**
*What should have happend after following the steps above.*

**What actually happens**
*Provide a concise message of what is actually happening.*

**Screenshots/Videos**
*If applicable, add screenshots/videos to help explain the problem.*

**Environment (please complete the following information):**
- OS: [e.g. Windows]
- Browser [e.g. chrome version 50, IE11]
- Zionbuilder Version [e.g. 1.0.0]

**Additional context**
*Add any other context about the problem here.*

**Comment by raluseru** [comment]
Hi, 

We cannot reproduce the bug you have open. Can you please give a more detailed explanation of the conditions in which this issue is reproducing? For example, on Zion Builder Admin Dashboard, there is the "system info" tab from where you can copy and paste the information about your system environment. Also , do you have any errors in your console?

Thank you in advance for your answer!

**Comment by zauan** [comment]
Closed due to inactivity.
