### ISSUE TITLE
Feature request: Custom html attributes for any element

### ISSUE THREAD

**Issue by Infusednl** [zionbuilder/zionbuilder#133]
## Summary

Being able to add custom html attributes to any element. This would allows easy integration of any plugin or javascript library that depends on custom attributes.

Oxygen released this in their version 3.5:

- https://oxygenbuilder.com/2020/08/25/oxygen-3-5-now-available/

### Motivation

Allow the integration plugins or javascript libraries that depend on custom html attributes.

**Comment by zauan** [comment]
Hi,

Thank you for your feedback. This seems like a great idea. Can you give me more details about this? When you mention that you would like data attributes for all elements, are you referring only to the element root HTML attribute? 

I am asking this because it would be easy for us to just add data attributes to all element wrappers ( without the ability to add data attributes to inner HTML tags ) and this could be done in the next update.

Thank you,
Stefan

**Comment by Infusednl** [comment]
Hi Stefan,

With elements i refer to the elements we can drag & drop in Zion Builder. For now I think only the wrapper element should be enough. An exception could be an element that has child elements such as the slider element where we could add custom attributes to each slide for example.

But for now only the wrapper element alone would allow a lot of creative freedom.

**Comment by balakumarshanmugam** [comment]
Hi Stefan,

Also please add ability to add ACF data to html attributes too. Just like we can map a ACF field to text element, please add ability to map ACF data to html attribute of an element.

**Comment by zauan** [comment]
This was added in version 2.0.0. I will close this ticket
