### ISSUE TITLE
Experiencing FOUC as sometimes the page CSS is added in the footer

### ISSUE THREAD

**Issue by wplit** [zionbuilder/zionbuilder#621]
**Describe the bug**
I notice that the generated CSS for a page is sometimes added in the footer instead of the <head>
This causes the HTML on the page to be visible before the CSS has been applied, meaning we see the raw HTML for a split second when the page loads. it's not so obvious is using a theme where the main structure of the site is coming from the theme, but when using Zion Builder Pro to build everything from scratch

<img width="1426" alt="Screen Shot 2021-09-06 at 4 09 28 pm" src="https://user-images.githubusercontent.com/43051571/132168701-fedd258b-34e2-48f8-983a-86e592337b8c.png">

**Expected behavior**
The CSS should be in the <head> to prevent content ever being visible unstyled.

**Comment by zauan** [comment]
Hi there,

the CSS is loaded in the footer the first time the page css is generated. This is because we need to parse the entire page and see what CSS is needed.

This is actually a performance improvement as the CSS and various CSS related code only runs if it is actually needed.

Please let me know if you experience problems outside of this behaviour.

Best regards,
Stefan

**Comment by wplit** [comment]
I see. Thanks, I hadn't checked the code and as it only appeared to be only happening sporadically had assumed something was going wrong somewhere. Thanks for clarifying.
